framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    cache:
        default_redis_provider: '%env(REDIS_URL)%'

    #esi: true
    #fragments: true
    php_errors:
        log: true
