version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/www/sf4
        depends_on:
          - php

    postgres:
        image: postgres
        container_name: sf4_postgres
        volumes:
            - .docker/data/postgre:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: sf4
    redis:
      image: redis
      container_name: sf4_redis

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - .:/home/www/sf4
        depends_on:
          - postgres
          - redis
