monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
        nested:
            type: stream
            path: "php://stdout"
            level: debug
            formatter: 'monolog.formatter.json'
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "php://stdout"
            formatter: 'monolog.formatter.json'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
